version: '3'
services:
  examen-vehiculo:
    build: examen-vehiculo
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://examen_vehiculo:3306/matriculacionfinal?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 123
    restart: always
    depends_on:
      examen_vehiculo:
        condition: service_healthy

  examen_vehiculo:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: matriculacionfinal
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: examen_vehiculo
      MYSQL_ROOT_PASSWORD: 123
    depends_on:
      - examen_vehiculo
